# Generated by Django 4.2.30 on 2026-05-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_add_default_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.CharField(default='default.jpg', max_length=100),
        ),
    ]
